version: '3.7'
services:
  postgres:
    image: "postgres:11"
    environment:
      TZ: "America/Recife"
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: "sinelacto"
    ports:
      - "5432:5432"
    volumes:
      - ./volume-postgres:/var/lib/postgresql/data